#!/bin/sh

[ $# -ge 1 ] || exit 1

if [ "$1" == "-r" ]; then
  remote=$2
  shift 2
else
  if [ "$1" == "push" ]; then
    remote=st-db_tools-up
  else
    remote=st-db_tools
  fi
fi

[ -n `git rev-parse --show-toplevel` ] || exit 2

cd `git rev-parse --show-toplevel`

git subtree $@ -P db/db_tools $remote master

# vi: expandtab ts=2 sw=2
